name: 'waggers-action'
description: 'Swagger fuzzing'
branding:
  icon: 'shield-off'
  color: 'red'
inputs:
  url:
    description: 'URL of Swagger description'
    required: true
  fuzzcount:
    description: 'How many times should an URL path be fuzzed. The default is 1.'
    required: false
  headers:
    description: 'Custom HTTP headers separated by comma.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.fuzzcount }}
    - ${{ inputs.headers }}
